[build] Fix the csproj so it compiles with newer monos
If we don't have a valid icon we should not specify this.

It's better than failing builds with:
	```[7:04:36] 	CSC: error CS7064: Error opening icon file `.'. Access to the path '.' is denied.```